CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(100) NOT NULL,
  "password" varchar(100) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "created_by" int NOT NULL,
  "updated_by" int NOT NULL,
  "deleted_by" int NOT NULL
);

CREATE TABLE "units" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "symbol" varchar(20) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "created_by" int NOT NULL
);

CREATE TABLE "customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(100) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "created_by" int NOT NULL,
  "updated_by" int NOT NULL,
  "deleted_by" int NOT NULL
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_id" int NOT NULL,
  "name" varchar(100) NOT NULL,
  "price" numeric(12,2) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "created_by" int NOT NULL,
  "updated_by" int NOT NULL,
  "deleted_by" int NOT NULL
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "customer_id" int NOT NULL,
  "invoice_number" varchar(50) NOT NULL,
  "transaction_date" date NOT NULL,
  "subtotal" numeric(12,2) DEFAULT 0,
  "tax_percent" numeric(12,2) DEFAULT 0,
  "tax_amount" numeric(12,2) DEFAULT 0,
  "grand_total" numeric(12,2) DEFAULT 0,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "transaction_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL,
  "price" numeric(12,2) NOT NULL,
  "total" numeric(12,2) NOT NULL
);

ALTER TABLE "transactions" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transaction_items" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "transaction_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("id");

ALTER TABLE "units" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "customers" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "customers" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "customers" ADD FOREIGN KEY ("deleted_by") REFERENCES "users" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("deleted_by") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("deleted_by") REFERENCES "users" ("id");
